CREATE DATABASE IF NOT EXISTS wh_s1_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wh_s2_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wh_s3_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wh_s4_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wh_app'@'%' IDENTIFIED BY 'wh_app_secret';
GRANT ALL PRIVILEGES ON wh_s1_db.* TO 'wh_app'@'%';
GRANT ALL PRIVILEGES ON wh_s2_db.* TO 'wh_app'@'%';
GRANT ALL PRIVILEGES ON wh_s3_db.* TO 'wh_app'@'%';
GRANT ALL PRIVILEGES ON wh_s4_db.* TO 'wh_app'@'%';
FLUSH PRIVILEGES;
