<?php

return [
    'gateway_url' => rtrim((string) env('GATEWAY_INTERNAL_URL', 'http://wh-gateway'), '/'),

    'refresh_before_expiry_seconds' => (int) env('PORTAL_TOKEN_REFRESH_BUFFER', 120),

    'module_icons' => [
        'dashboard' => 'layout-grid',
        'front_desk' => 'bed-double',
        'fb' => 'utensils-crossed',
        'inventory' => 'package',
        'consumption' => 'coffee',
        'group_bookings' => 'users-round',
        'hr' => 'user-cog',
        'payroll' => 'wallet',
        'finance' => 'file-bar-chart',
        'admin' => 'shield-check',
        'general' => 'zap',
    ],

    /*
    | Sidebar modules — filtered by user permissions (any match shows module).
    | Routes without Phase 1+ pages render Modules/Placeholder until implemented.
    */
    'modules' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'layout-grid',
            'route' => 'dashboard',
            'permissions' => ['S4.bi.dashboards.read', 'S4.bi.reports.read'],
            'phase' => 0,
        ],
        [
            'key' => 'front_desk',
            'label' => 'Front desk',
            'icon' => 'bed-double',
            'route' => 'front-desk.rooms.index',
            'permissions' => ['S3.hotel.rooms.read', 'S3.hotel.reservations.read', 'S3.hotel.folios.read'],
            'phase' => 1,
            'children' => [
                ['key' => 'rooms', 'label' => 'Room status', 'route' => 'front-desk.rooms.index', 'permissions' => ['S3.hotel.rooms.read']],
                ['key' => 'reservations', 'label' => 'Reservations', 'route' => 'front-desk.reservations.index', 'permissions' => ['S3.hotel.reservations.read']],
                ['key' => 'guests', 'label' => 'Guests', 'route' => 'front-desk.guests.index', 'permissions' => ['S3.hotel.guests.read']],
                ['key' => 'check_in', 'label' => 'Check in guest', 'route' => 'front-desk.check-in.create', 'permissions' => ['S3.hotel.checkinout.write', 'S3.hotel.reservations.write']],
                ['key' => 'folios', 'label' => 'Folios', 'route' => 'front-desk.folios.index', 'permissions' => ['S3.hotel.folios.read']],
                ['key' => 'cashier_shifts', 'label' => 'Cashier shifts', 'route' => 'front-desk.cashier-shifts.index', 'permissions' => ['S3.hotel.cashier.read']],
                ['key' => 'settings', 'label' => 'Hotel settings', 'route' => 'front-desk.settings.index', 'permissions' => ['S3.hotel.rooms.read']],
            ],
        ],
        [
            'key' => 'fb',
            'label' => 'Restaurant and F&B',
            'icon' => 'utensils-crossed',
            'route' => 'fb.menu.index',
            'permissions' => ['S3.restaurant.orders.read', 'S3.restaurant.menu.read'],
            'phase' => 2,
            'children' => [
                ['key' => 'menu', 'label' => 'Menu', 'route' => 'fb.menu.index', 'permissions' => ['S3.restaurant.menu.read']],
                ['key' => 'orders', 'label' => 'Orders', 'route' => 'fb.orders.index', 'permissions' => ['S3.restaurant.orders.read']],
                ['key' => 'orders_create', 'label' => 'New order', 'route' => 'fb.orders.create', 'permissions' => ['S3.restaurant.orders.write']],
                ['key' => 'settings', 'label' => 'Catalog admin', 'route' => 'fb.settings.index', 'permissions' => ['S3.restaurant.menu.write']],
            ],
        ],
        [
            'key' => 'inventory',
            'label' => 'Inventory and procurement',
            'icon' => 'package',
            'route' => 'inventory.items.index',
            'permissions' => ['S3.inventory.items.read', 'S3.inventory.purchase_orders.read'],
            'phase' => 3,
            'children' => [
                ['key' => 'items', 'label' => 'Items', 'route' => 'inventory.items.index', 'permissions' => ['S3.inventory.items.read']],
                ['key' => 'alerts', 'label' => 'Stock alerts', 'route' => 'inventory.alerts.index', 'permissions' => ['S3.inventory.items.read']],
                ['key' => 'valuation', 'label' => 'Valuation', 'route' => 'inventory.valuation.index', 'permissions' => ['S3.inventory.reports.read']],
                ['key' => 'suppliers', 'label' => 'Suppliers', 'route' => 'inventory.suppliers.index', 'permissions' => ['S3.inventory.suppliers.read']],
                ['key' => 'purchase_orders', 'label' => 'Purchase orders', 'route' => 'inventory.purchase-orders.index', 'permissions' => ['S3.inventory.purchase_orders.read']],
            ],
        ],
        [
            'key' => 'consumption',
            'label' => 'Staff meals',
            'icon' => 'coffee',
            'route' => 'consumption.periods.index',
            'permissions' => ['S3.restaurant.consumption.read'],
            'phase' => 4,
        ],
        [
            'key' => 'group_bookings',
            'label' => 'Group bookings',
            'icon' => 'users-round',
            'route' => 'group-bookings.index',
            'permissions' => ['S3.hotel.group_bookings.read'],
            'phase' => 5,
            'children' => [
                ['key' => 'list', 'label' => 'All bookings', 'route' => 'group-bookings.index', 'permissions' => ['S3.hotel.group_bookings.read']],
                ['key' => 'create', 'label' => 'Create booking', 'route' => 'group-bookings.create', 'permissions' => ['S3.hotel.group_bookings.create']],
            ],
        ],
        [
            'key' => 'hr',
            'label' => 'HR',
            'icon' => 'user-cog',
            'route' => 'hr.employees.index',
            'permissions' => [
                'S2.workforce.employees.read',
                'S2.workforce.leave_requests.read',
                'S2.workforce.attendance.read',
                'S2.hr.departments.read',
                'S2.workforce.positions.read',
                'S2.workforce.overtime.read',
                'S2.workforce.offboarding.read',
                'S2.workforce.leave_types.read',
            ],
            'phase' => 6,
            'children' => [
                ['key' => 'employees', 'label' => 'Employees', 'route' => 'hr.employees.index', 'permissions' => ['S2.workforce.employees.read']],
                ['key' => 'departments', 'label' => 'Departments', 'route' => 'hr.departments.index', 'permissions' => ['S2.hr.departments.read']],
                ['key' => 'positions', 'label' => 'Positions', 'route' => 'hr.positions.index', 'permissions' => ['S2.workforce.positions.read']],
                ['key' => 'overtime', 'label' => 'Overtime', 'route' => 'hr.overtime.index', 'permissions' => ['S2.workforce.overtime.read']],
                ['key' => 'offboarding', 'label' => 'Offboarding', 'route' => 'hr.offboarding.index', 'permissions' => ['S2.workforce.offboarding.read']],
                ['key' => 'settings', 'label' => 'Settings', 'route' => 'hr.settings.index', 'permissions' => ['S2.workforce.leave_types.read', 'S2.workforce.overtime.read', 'S2.hr.assets.read']],
                ['key' => 'leave', 'label' => 'Leave requests', 'route' => 'hr.leave.index', 'permissions' => ['S2.workforce.leave_requests.read']],
                ['key' => 'attendance', 'label' => 'Attendance', 'route' => 'hr.attendance.index', 'permissions' => ['S2.workforce.attendance.read']],
            ],
        ],
        [
            'key' => 'payroll',
            'label' => 'Payroll',
            'icon' => 'wallet',
            'route' => 'payroll.runs.index',
            'permissions' => ['S2.workforce.payroll_runs.read', 'S2.workforce.severance.read'],
            'phase' => 6,
            'children' => [
                ['key' => 'runs', 'label' => 'Payroll runs', 'route' => 'payroll.runs.index', 'permissions' => ['S2.workforce.payroll_runs.read']],
                ['key' => 'severance', 'label' => 'Severance', 'route' => 'payroll.severance.index', 'permissions' => ['S2.workforce.severance.read']],
            ],
        ],
        [
            'key' => 'finance',
            'label' => 'Finance',
            'icon' => 'file-bar-chart',
            'route' => 'finance.reports.index',
            'permissions' => [
                'S4.finance.payables.read',
                'S4.finance.reports.read',
                'S4.finance.journal_entries.read',
                'S4.finance.receivables.read',
                'S4.bi.dashboards.read',
            ],
            'phase' => 7,
            'children' => [
                ['key' => 'reports', 'label' => 'Reports', 'route' => 'finance.reports.index', 'permissions' => ['S4.finance.reports.read']],
                ['key' => 'journals', 'label' => 'Journals', 'route' => 'finance.journals.index', 'permissions' => ['S4.finance.journal_entries.read']],
                ['key' => 'payables', 'label' => 'Payables', 'route' => 'finance.payables.index', 'permissions' => ['S4.finance.payables.read']],
                ['key' => 'receivables', 'label' => 'Receivables', 'route' => 'finance.receivables.index', 'permissions' => ['S4.finance.receivables.read']],
                ['key' => 'budget', 'label' => 'Budget', 'route' => 'finance.budget.index', 'permissions' => ['S4.finance.budgets.read', 'S4.bi.reports.read']],
                ['key' => 'fiscal_periods', 'label' => 'Fiscal periods', 'route' => 'finance.fiscal-periods.index', 'permissions' => ['S4.finance.fiscal_periods.read']],
                ['key' => 'executive_dashboard', 'label' => 'Executive dashboard', 'route' => 'finance.dashboard.executive', 'permissions' => ['S4.bi.dashboards.read']],
                ['key' => 'operations_dashboard', 'label' => 'Operations dashboard', 'route' => 'finance.dashboard.operations', 'permissions' => ['S4.bi.dashboards.read']],
            ],
        ],
        [
            'key' => 'admin',
            'label' => 'Administration',
            'icon' => 'shield-check',
            'route' => 'admin.users.index',
            'permissions' => [
                'S1.identity.users.read',
                'S1.identity.roles.read',
                'S1.identity.permissions.read',
                'S1.identity.audit_logs.read',
            ],
            'phase' => 8,
            'children' => [
                ['key' => 'users', 'label' => 'Users', 'route' => 'admin.users.index', 'permissions' => ['S1.identity.users.read']],
                ['key' => 'roles', 'label' => 'Roles & permissions', 'route' => 'admin.roles.index', 'permissions' => ['S1.identity.roles.read']],
                ['key' => 'permissions', 'label' => 'Permission catalog', 'route' => 'admin.permissions.index', 'permissions' => ['S1.identity.permissions.read']],
                ['key' => 'audit', 'label' => 'Audit logs', 'route' => 'admin.audit.index', 'permissions' => ['S1.identity.audit_logs.read']],
            ],
        ],
    ],

    /*
    | Task-first shortcuts — shown above module nav when route exists and user has permission.
    */
    'tasks' => [
        [
            'key' => 'check_in_guest',
            'label' => 'Check in guest',
            'route' => 'front-desk.check-in.create',
            'module' => 'front_desk',
            'permissions' => ['S3.hotel.checkinout.write', 'S3.hotel.reservations.write'],
        ],
        [
            'key' => 'settle_folio',
            'label' => 'Settle folio',
            'route' => 'front-desk.folios.index',
            'module' => 'front_desk',
            'permissions' => ['S3.hotel.folios.read', 'S3.hotel.folios.write'],
        ],
        [
            'key' => 'room_status',
            'label' => 'Room status',
            'route' => 'front-desk.rooms.index',
            'module' => 'front_desk',
            'permissions' => ['S3.hotel.rooms.read'],
        ],
        [
            'key' => 'approve_po',
            'label' => 'Approve purchase order',
            'route' => 'inventory.purchase-orders.index',
            'module' => 'inventory',
            'permissions' => ['S3.inventory.purchase_orders.approve'],
        ],
        [
            'key' => 'create_po',
            'label' => 'Create purchase order',
            'route' => 'inventory.purchase-orders.create',
            'module' => 'inventory',
            'permissions' => ['S3.inventory.purchase_orders.write'],
        ],
        [
            'key' => 'settle_payables',
            'label' => 'Settle payables',
            'route' => 'finance.payables.index',
            'module' => 'finance',
            'permissions' => ['S4.finance.payables.settle', 'S4.finance.payables.read'],
        ],
        [
            'key' => 'post_fb_to_folio',
            'label' => 'Post F&B to folio',
            'route' => 'fb.orders.create',
            'module' => 'fb',
            'permissions' => ['S3.restaurant.orders.write'],
        ],
        [
            'key' => 'view_menu',
            'label' => 'View menu',
            'route' => 'fb.menu.index',
            'module' => 'fb',
            'permissions' => ['S3.restaurant.menu.read'],
        ],
        [
            'key' => 'staff_meals',
            'label' => 'Staff meal period',
            'route' => 'consumption.periods.index',
            'module' => 'consumption',
            'permissions' => ['S3.restaurant.consumption.read'],
        ],
        [
            'key' => 'create_group',
            'label' => 'Create group booking',
            'route' => 'group-bookings.create',
            'module' => 'group_bookings',
            'permissions' => ['S3.hotel.group_bookings.create'],
        ],
        [
            'key' => 'create_payroll_run',
            'label' => 'Create payroll run',
            'route' => 'payroll.runs.create',
            'module' => 'payroll',
            'permissions' => ['S2.workforce.payroll_runs.create'],
        ],
        [
            'key' => 'record_attendance',
            'label' => 'Record attendance',
            'route' => 'hr.attendance.index',
            'module' => 'hr',
            'permissions' => ['S2.workforce.attendance.read', 'S2.workforce.attendance.create'],
        ],
        [
            'key' => 'trial_balance',
            'label' => 'Trial balance',
            'route' => 'finance.reports.index',
            'module' => 'finance',
            'permissions' => ['S4.finance.reports.read'],
        ],
        [
            'key' => 'create_journal',
            'label' => 'Create journal',
            'route' => 'finance.journals.create',
            'module' => 'finance',
            'permissions' => ['S4.finance.journal_entries.create'],
        ],
    ],
];
