<?php

return [
    'reports' => [
        ['slug' => 'trial_balance', 'name' => 'Trial Balance', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'income_statement', 'name' => 'Income Statement', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'balance_sheet', 'name' => 'Balance Sheet', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'cash_flow', 'name' => 'Cash Flow Statement', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'gl_detail', 'name' => 'General Ledger Detail', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'ar_aging', 'name' => 'AR Aging', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'ap_aging', 'name' => 'AP Aging', 'category' => 'finance', 'module' => 'report'],
        ['slug' => 'revenue_by_source', 'name' => 'Revenue by Source Module', 'category' => 'finance', 'module' => 'bi'],
        ['slug' => 'hospitality_snapshot', 'name' => 'Hospitality Snapshot', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'occupancy', 'name' => 'Room Occupancy', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'reservation_pipeline', 'name' => 'Reservation Pipeline', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'fb_sales', 'name' => 'F&B Sales', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'fb_sales_by_customer_type', 'name' => 'F&B Sales by Customer Type', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'hr_employee_directory', 'name' => 'Employee Directory', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'payroll_summary', 'name' => 'Payroll Summary Sheet', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'inventory_status', 'name' => 'Inventory Status', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'inventory_expiry_alert', 'name' => 'Inventory Expiry Alert', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'inventory_valuation', 'name' => 'Inventory Valuation (FIFO)', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'cashier_shift', 'name' => 'Cashier Shift Report', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'purchase_order_status', 'name' => 'Purchase Order Status', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'folio_outstanding', 'name' => 'Outstanding Folios', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'room_revenue_mix', 'name' => 'Room Revenue Mix', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'payroll_snapshot', 'name' => 'Payroll Snapshot', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'headcount_by_department', 'name' => 'Headcount by Department', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'leave_summary', 'name' => 'Leave Summary', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'leave_balance', 'name' => 'Leave Balance', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'leave_utilisation', 'name' => 'Leave Utilisation', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'payroll_pension', 'name' => 'Pension Contribution', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'payroll_overtime', 'name' => 'Overtime Report', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'hr_disciplinary_history', 'name' => 'Disciplinary History', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'hr_asset_clearance', 'name' => 'Asset Clearance', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'inventory_stock_movement', 'name' => 'Stock Movement', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'employee_consumption', 'name' => 'Employee Consumption', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'guest_folio_invoice', 'name' => 'Guest Folio Invoice', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'payroll_payslip', 'name' => 'Individual Payslip', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'hr_guarantor_letter', 'name' => 'Guarantor Letter', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'supplier_payment_history', 'name' => 'Supplier Payment History', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'event_fb_billing', 'name' => 'Event F&B Billing', 'category' => 'hospitality', 'module' => 'bi'],
        ['slug' => 'payroll_cost_trend', 'name' => 'Payroll Cost Trend', 'category' => 'workforce', 'module' => 'bi'],
        ['slug' => 'executive_dashboard', 'name' => 'Executive Dashboard', 'category' => 'executive', 'module' => 'dashboard'],
        ['slug' => 'operations_dashboard', 'name' => 'Operations Dashboard', 'category' => 'executive', 'module' => 'dashboard'],
        ['slug' => 'budget_variance', 'name' => 'Budget Variance', 'category' => 'executive', 'module' => 'bi'],
        ['slug' => 'kpi_scorecard', 'name' => 'KPI Scorecard', 'category' => 'executive', 'module' => 'bi'],
    ],
];
